### ISSUE TITLE
Output folder for generated sources

### ISSUE THREAD

**Issue by mishadoff** [xsc/lein-thriftc#2]
Is there any way to specify output folder for generated sources? (`-out` option for thrift)
It is use case when needed to generate sources in `src/gen` folder 

I looked at the code but seems the `target-path` option is always overriden by `merge`

**Comment by xsc** [comment]
`lein-thrift` puts its stuff into a subdirectory `thrift-java` of your project's `:target-path` - there is currently no special option within the `:thriftc` map.

Do you really need this functionality, i.e. do you really need fine-grained control over _where_ on the classpath they end up?

**Comment by mishadoff** [comment]
That may be useful when we need to generate sources and commit them, and someone is able to compile the code even without thrift compiler (target folder is often ignored in git)

Though it's not big deal, I can generate sources using `thrift` and just copy them to the place I want.

**Comment by xsc** [comment]
I see. I'm personally not a fan of committing auto-generated code but I'll include the possibility to customize the output path.

**Comment by xsc** [comment]
Released as

```clojure
[lein-thriftc "0.2.3"]
```

(I finally managed to get a list of all open tickets in my repositories - needless to say, a few were forgotten...)
